# -*- coding: utf-8 -*-
"""tennis bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TYu1VArWXQlbnjke84AVKOEJXMPyKkI8
"""

# ===================================================================
# VERSION AMÉLIORÉE (GARDÉE À L'IDENTIQUE)
# avec PHOTO D'UN DISTRIBUTEUR DE BALLES DE TENNIS en page 1
# ===================================================================

# 1. Installation des bibliothèques manquantes (décommenter si besoin)
# !pip install networkx plotly ipywidgets pandas numpy matplotlib

import ipywidgets as widgets
from IPython.display import display, Image, HTML, clear_output
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import random
from google.colab import drive
drive.mount('/content/drive')
# Style CSS global pour un rendu plus esthétique
display(HTML("""
<style>
    .main-container { font-family: 'Segoe UI', Arial, sans-serif; }
    .card { background: white; border-radius: 15px; padding: 20px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); margin: 10px 0; }
    .btn-primary { background: linear-gradient(45deg, #FF6B35, #F7931E); color: white; border: none; padding: 12px 30px; border-radius: 30px; font-size: 18px; font-weight: bold; cursor: pointer; }
    .btn-primary:hover { transform: scale(1.02); box-shadow: 0 5px 15px rgba(247, 147, 30, 0.4); }
    .title-glow { color: #2C3E50; text-shadow: 2px 2px 4px rgba(0,0,0,0.1); }
    .user-badge { background: #2C3E50; color: white; padding: 8px 20px; border-radius: 50px; display: inline-block; }
</style>
"""))

# Variable globale pour stocker les données utilisateur
user_data = {}

# ============================================================
# ÉTAPE 1 : ÉCRAN D'ACCUEIL AVEC IMAGE (DISTRIBUTEUR) ET BOUTON
# ============================================================
def show_welcome():
    clear_output(wait=True)
    # ✅ ICI : Photo d'un VRAI distributeur de balles de tennis (Unsplash)
    display(HTML("""
    <div class="main-container" style="text-align: center;">
        <div class="card">
            <img src="/content/drive/MyDrive/machine.jpg"
                 style="width: 100%; max-height: 400px; object-fit: cover; border-radius: 10px;"
                 alt="Distributeur de balles de tennis">
            <h1 class="title-glow" style="font-size: 2.8rem; margin-top: 20px;">🎾 Distributeur Pro</h1>
            <p style="font-size: 1.2rem; color: #555;">
                Cette machine intelligent envoie des balles avec une <b>vitesse variable</b>, un <b>effet lifté</b>
                et une <b>précision millimétrique</b>. Elle analyse ton niveau pour te proposer des exercices sur mesure.
            </p>
            <div style="background: #FFF3E0; padding: 15px; border-radius: 10px; margin: 15px 0;">
                <h2 style="color: #E67E22; font-size: 2rem;">🔥 Est-ce que tu veux qu'on commence l'aventure ?</h2>
            </div>
            <button id="start-btn" class="btn-primary" style="font-size: 1.5rem; padding: 15px 40px;">
                🚀 Commencer notre aventure
            </button>
        </div>
    </div>
    """))

    # Création du bouton interactif (car le HTML brut ne déclenche pas Python)
    btn = widgets.Button(description="🚀 Commencer notre aventure",
                         button_style='success',
                         layout=widgets.Layout(width='auto', padding='15px', margin='10px auto'))
    btn.style.button_color = '#F7931E'
    display(btn)
    btn.on_click(lambda b: show_form())

# ============================================================
# ÉTAPE 2 : FORMULAIRE UTILISATEUR
# ============================================================
def show_form():
    clear_output(wait=True)
    display(HTML("<div class='main-container'><div class='card'><h2>📝 Crée ton profil de joueur</h2></div>"))

    # Widgets du formulaire
    nom = widgets.Text(description="👤 Nom :", placeholder="Ex: Rafael", layout=widgets.Layout(width='80%'))
    age = widgets.IntSlider(value=25, min=8, max=80, step=1, description="🎂 Âge :", continuous_update=False)
    anciennete = widgets.Dropdown(
        options=['Moins d\'1 an', '1-3 ans', '3-5 ans', '5-10 ans', 'Plus de 10 ans'],
        description="📅 Ancienneté :",
        layout=widgets.Layout(width='80%')
    )
    frequence = widgets.Dropdown(
        options=['1-2 fois/semaine', '3-4 fois/semaine', '5-6 fois/semaine', 'Tous les jours'],
        description="📆 Fréquence :",
        layout=widgets.Layout(width='80%')
    )
    niveau = widgets.Dropdown(
        options=['Débutant', 'Intermédiaire', 'Avancé'],
        description="🏅 Niveau :",
        layout=widgets.Layout(width='80%')
    )

    btn_valider = widgets.Button(description="✅ Valider mon profil",
                                 button_style='primary',
                                 layout=widgets.Layout(width='auto', padding='10px 30px'))

    # Affichage
    display(nom, age, anciennete, frequence, niveau, btn_valider)

    def on_submit(b):
        global user_data
        user_data = {
            'Nom': nom.value if nom.value else "Joueur",
            'Âge': age.value,
            'Ancienneté': anciennete.value,
            'Fréquence': frequence.value,
            'Niveau': niveau.value
        }
        # Ajustement des paramètres machine selon le niveau
        if user_data['Niveau'] == 'Débutant':
            base_speed = 60
        elif user_data['Niveau'] == 'Intermédiaire':
            base_speed = 85
        else:
            base_speed = 110
        user_data['base_speed'] = base_speed

        show_dashboard(user_data)

    btn_valider.on_click(on_submit)
    display(HTML("</div>"))

# ============================================================
# ÉTAPE 3 : TABLEAU DE BORD COMPLET (3 ONGLETS)
# ============================================================
# Variables globales pour l'état du dashboard
shot_history = []

def show_dashboard(data):
    global shot_history
    shot_history = []  # Réinitialiser l'historique

    clear_output(wait=True)

    # Bannière utilisateur
    display(HTML(f"""
    <div class='main-container'>
        <div style='background: linear-gradient(90deg, #2C3E50, #4CA1AF); color: white; padding: 15px 25px; border-radius: 10px; margin-bottom: 20px;'>
            <span style='font-size: 1.5rem;'>🎾 Bienvenue, <b>{data['Nom']}</b> !</span>
            <span style='float: right; background: rgba(255,255,255,0.2); padding: 5px 15px; border-radius: 20px;'>
                Niveau : {data['Niveau']} | Vitesse de base : {data['base_speed']} km/h
            </span>
        </div>
    </div>
    """))

    # --- Création des onglets ---
    tab = widgets.Tab()
    tab.children = [
        create_tree_tab(),
        create_control_tab(data),
        create_history_tab()
    ]
    tab.set_title(0, '🔧 Arborescence')
    tab.set_title(1, '🎯 Pilotage & Performance')
    tab.set_title(2, '📊 Historique')

    display(tab)

# ----- Onglet 1 : Arborescence (NetworkX) -----
def create_tree_tab():
    out = widgets.Output()
    with out:
        # Création du graphe
        G = nx.DiGraph()
        G.add_node("Distributeur\nIntelligent", color='#3498DB')
        G.add_node("Système\nÉlectronique", color='#2ECC71')
        G.add_node("Mécanique\n(Bras)", color='#F1C40F')
        G.add_node("Logiciel\nd'Analyse", color='#9B59B6')

        G.add_node("Vitesse\nVariable", color='#E67E22')
        G.add_node("Effet\n(Lift/Slice)", color='#E74C3C')
        G.add_node("Précision\n(GPS/Cam)", color='#1ABC9C')
        G.add_node("Interface\nUtilisateur", color='#34495E')

        # Arêtes
        edges = [("Distributeur\nIntelligent", "Système\nÉlectronique"),
                 ("Distributeur\nIntelligent", "Mécanique\n(Bras)"),
                 ("Distributeur\nIntelligent", "Logiciel\n d'Analyse"),
                 ("Système\nÉlectronique", "Vitesse\nVariable"),
                 ("Système\nÉlectronique", "Effet\n(Lift/Slice)"),
                 ("Mécanique\n(Bras)", "Précision\n(GPS/Cam)"),
                 ("Logiciel\n d'Analyse", "Interface\nUtilisateur")]
        G.add_edges_from(edges)

        # Positionnement en arbre
        pos = nx.spring_layout(G, seed=42, k=1.5)

        # Couleurs
        node_colors = [G.nodes[n].get('color', '#95A5A6') for n in G.nodes()]

        plt.figure(figsize=(10, 7))
        nx.draw(G, pos, with_labels=True, node_color=node_colors,
                node_size=3000, font_size=9, font_weight='bold',
                edge_color='gray', arrowsize=20, arrowstyle='->',
                font_color='white', linewidths=2, edgecolors='white')
        plt.title("Arborescence technique de la machine", fontsize=16, fontweight='bold')
        plt.tight_layout()
        plt.show()
    return out

# ----- Onglet 2 : Pilotage (Curseurs + Graphique interactif) -----
def create_control_tab(data):
    out = widgets.Output()

    # Curseurs
    speed_slider = widgets.IntSlider(value=data['base_speed'], min=30, max=150, step=1,
                                     description='⚡ Vitesse (km/h) :',
                                     layout=widgets.Layout(width='70%'))
    spin_slider = widgets.IntSlider(value=5, min=0, max=15, step=1,
                                    description='🌀 Effet (rotation) :',
                                    layout=widgets.Layout(width='70%'))

    # Bouton de tir
    fire_btn = widgets.Button(description='🏸 Lancer la balle !',
                              button_style='danger',
                              layout=widgets.Layout(width='auto', padding='10px 25px'))

    # Zone de sortie pour le graphique
    graph_output = widgets.Output()

    # Fonction pour mettre à jour le graphique
    def update_shot(b=None):
        global shot_history
        with graph_output:
            clear_output(wait=True)

            # Simuler une trajectoire en fonction des paramètres
            speed = speed_slider.value
            spin = spin_slider.value
            # La précision varie légèrement selon le niveau (plus le niveau est haut, plus la dispersion est faible)
            if data['Niveau'] == 'Débutant':
                dispersion = 8
            elif data['Niveau'] == 'Intermédiaire':
                dispersion = 4
            else:
                dispersion = 1.5

            # Génération de la balle (coordonnées x, y)
            x_landing = np.random.normal(0, dispersion)  # Position en largeur
            y_landing = np.random.normal(10 + (speed/10), 2)  # Profondeur

            # Enregistrement dans l'historique
            shot_history.append({
                'Tir': len(shot_history)+1,
                'Vitesse': speed,
                'Effet': spin,
                'Précision (écart cm)': round(abs(x_landing)*2, 1),
                'Zone': 'Cible' if abs(x_landing) < 3 else 'Hors cible'
            })
            if len(shot_history) > 5:
                shot_history.pop(0)

            # Création du graphique Plotly
            fig = go.Figure()

            # Cible (cercles concentriques)
            fig.add_shape(type="circle", xref="x", yref="y", x0=-8, y0=5, x1=8, y1=21,
                          line_color="LightGray", fillcolor="rgba(255,0,0,0.05)")
            fig.add_shape(type="circle", xref="x", yref="y", x0=-4, y0=9, x1=4, y1=17,
                          line_color="Gray", fillcolor="rgba(255,0,0,0.1)")
            fig.add_shape(type="circle", xref="x", yref="y", x0=-1.5, y0=11.5, x1=1.5, y1=14.5,
                          line_color="DarkRed", fillcolor="rgba(255,0,0,0.3)")

            # Point d'impact
            fig.add_trace(go.Scatter(
                x=[x_landing],
                y=[y_landing],
                mode='markers+text',
                marker=dict(size=20, color='#E74C3C', line=dict(width=2, color='Black')),
                text=[f"{speed} km/h"],
                textposition="top center",
                name='Balle'
            ))

            # Trajectoire (ligne pointillée)
            fig.add_trace(go.Scatter(
                x=[0, x_landing],
                y=[0, y_landing],
                mode='lines',
                line=dict(dash='dash', color='#3498DB', width=3),
                name='Trajectoire'
            ))

            fig.update_layout(
                title=f"🎯 Simulation du tir (Vitesse: {speed} km/h, Effet: {spin})",
                xaxis_title="Largeur du court (m)",
                yaxis_title="Profondeur (m)",
                xaxis=dict(range=[-12, 12], zeroline=True),
                yaxis=dict(range=[-2, 25], zeroline=True),
                height=500,
                plot_bgcolor='rgba(240,240,240,0.8)',
                shapes=[dict(type='rect', xref='paper', yref='paper', x0=0, y0=0, x1=1, y1=1, fillcolor='rgba(0,0,0,0)', line_width=0)]
            )

            # Ajout d'une jauge de performance (vitesse actuelle vs max)
            fig.add_annotation(
                x=10, y=22,
                text=f"Niveau: {data['Niveau']}<br>Dispersion: {dispersion} cm",
                showarrow=False,
                font=dict(size=12, color="white"),
                bgcolor="#2C3E50",
                bordercolor="black",
                borderwidth=1
            )

            fig.show()

    # Lier le bouton et les curseurs (mise à jour auto quand on change un slider)
    speed_slider.observe(update_shot, 'value')
    spin_slider.observe(update_shot, 'value')
    fire_btn.on_click(update_shot)

    # Assemblage de l'onglet
    with out:
        display(HTML("<div class='card'><h3>🎮 Contrôle de la machine</h3></div>"))
        display(speed_slider)
        display(spin_slider)
        display(fire_btn)
        display(HTML("<hr>"))
        display(graph_output)

    # Tir initial pour afficher quelque chose
    update_shot(None)

    return out

# ----- Onglet 3 : Historique -----
def create_history_tab():
    out = widgets.Output()
    with out:
        display(HTML("<div class='card'><h3>📋 Derniers tirs enregistrés</h3></div>"))
        history_output = widgets.Output()
        display(history_output)

        # Fonction de mise à jour (appelée depuis le contrôle)
        def update_history():
            with history_output:
                clear_output(wait=True)
                if not shot_history:
                    display(HTML("<p><i>Aucun tir enregistré pour le moment. Lance une balle !</i></p>"))
                    return
                df = pd.DataFrame(shot_history)
                # Style du tableau
                display(df.style.background_gradient(cmap='Blues', subset=['Précision (écart cm)']))

        # On expose un moyen de rafraîchir. On va juste rafraîchir périodiquement ou on le lie.
        # Pour simplifier, on appelle update_history via un bouton.
        refresh_btn = widgets.Button(description="🔄 Rafraîchir l'historique", icon='refresh')
        refresh_btn.on_click(lambda b: update_history())
        display(refresh_btn)
        update_history()

        # On stocke la fonction dans l'objet out pour pouvoir l'appeler depuis l'onglet 2
        out.update_history = update_history

    return out

# ============================================================
# LANCEMENT DE L'APPLICATION
# ============================================================
show_welcome()